import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  icon: {
    position: 'absolute',
    zIndex: 1,
    backgroundColor: 'transparent',
    elevation: 5,
    marginTop: hp(4),
    marginLeft: wp(4),
  },
  editMainContainer: {
    backgroundColor: '#BAE9F4',
    paddingBottom: 30,
    borderBottomLeftRadius: wp(10),
    borderBottomEndRadius: wp(10),
    elevation: 5,
  },
  tapedit: {
    color: '#fff',
    alignSelf: 'center',
    // paddingBottom: 10,
  },
  imageContainer: {
    marginTop: hp(3),
    alignSelf: 'center',
  },
  image: {
    resizeMode: 'contain',
    alignSelf: 'center',
    width: wp(20),
    height: wp(25),
  },
  nameText: {
    color: '#fff',
    fontSize: 6,
    alignSelf: 'center',
  },
  ageText: {
    color: '#fff',
    fontSize: 4,
    alignSelf: 'center',
  },
  swapButton: {
    marginTop: hp(2),
    // width: wp(35),
    backgroundColor: '#F3B399',
    alignSelf: 'center',
    color: '#fff',
    paddingHorizontal: 20,
    borderRadius: wp(2),
    elevation: 5,
    paddingVertical: 1,
    height: hp(6),
    margin: 2,
  },
  edit: {
    marginTop: hp(2),
    backgroundColor: '#F3B399',
    color: '#fff',
    paddingHorizontal: 20,
    borderRadius: wp(10),
    elevation: 5,
  },

  afterBreakfast: {
    backgroundColor: '#FEB069',
    height: 30,
    width: wp(30),
    alignSelf: 'center',
    color: '#fff',
    paddingVertical: 2,
    paddingHorizontal: 10,
    bottom: 10,
  },
  afterDinner: {
    height: 30,
    width: wp(30),
    backgroundColor: '#E3B9DF',
    alignSelf: 'center',
    color: '#fff',
    paddingVertical: 2,
    paddingHorizontal: 10,
    bottom: 10,
  },
  editButton: {
    backgroundColor: '#5FBACF',
    height: 30,
    alignSelf: 'center',
    color: '#fff',
    width: wp(30),
    paddingVertical: 2,
    paddingHorizontal: 10,
    borderRadius: 5,
    paddingBottom: 10,
    bottom: hp(2),
  },
  tabletName: {
    paddingTop: 10,
    color: '#fff',
    fontSize: 6,
    //marginBottom: hp(2),
  },
  caroselImage: {
    height: hp(15),
    width: wp(15),
    resizeMode: 'contain',
  },
  caroselContainer: {
    backgroundColor: '#5FBACF',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: wp(5),
    width: wp(50),
    borderRadius: 30,
    marginHorizontal: 10,
    paddingVertical: 5,
    elevation: 3,
    marginBottom: 20,
  },
  cardBottom: {
    backgroundColor: '#fafafa',
    width: '100%',
    height: hp(10),
    borderBottomLeftRadius: 30,
    borderBottomEndRadius: 30,
    justifyContent: 'center',
    bottom: 0,
    position: 'absolute',
  },
  editContainer: {
    flex: 1,
    justifyContent: 'center',
    marginTop: hp(10),
  },
  courses: {
    paddingLeft: wp(5),
    paddingTop: hp(2),
    color: '#94D1E0',
    fontSize: 6,
  },
  horizontalCard: {
    flexDirection: 'row',
    //  backgroundColor: 'red',
  },
  tablet2: {
    width: wp(10),
    height: wp(10),
    justifyContent: 'center',
    //left: 5,
    marginTop: 10,
    alignSelf: 'center',
    //justifyContent: 'center',
    /// alignItems: 'center',
  },
  tablet: {
    flex: 1,
    width: wp(10),
    height: wp(10),
    marginTop: 10,
    right: 5,
    alignItems: 'center',
  },
  tabletList: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#5FBACF',
    width: wp(15),
    height: wp(15),
    borderRadius: 30,
  },
  tabletList1: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#FF9736',
    width: wp(15),
    height: wp(15),
    borderRadius: 30,
  },

  todayColor: {
    color: '#5FBACF',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // backgroundColor: 'red',
    paddingHorizontal: 2,
  },
  roundedCircle: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: '#FF9736',
    borderRadius: wp(15) / 2,
    width: wp(15),
    height: wp(15),
  },
  list1: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: '#82AEC0',
    borderRadius: wp(15) / 2,
    width: wp(15),
    height: wp(15),
  },
  list: {
    // paddingLeft: wp(5),
    padding: 10,
  },
  addReminder: {
    marginTop: hp(10),
    justifyContent: 'center',
    backgroundColor: '#5FBACF',
    alignItems: 'center',
    alignSelf: 'center',
    height: wp(12),
    width: wp(12),
    borderRadius: 60,
  },
  addButton: {
    fontSize: 8,
    color: '#fff',
  },
  withoutMadien: {
    marginTop: hp(5),
    width: wp(50),
    height: hp(40),
    backgroundColor: '#5FBACF',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  plusButton: {
    width: wp(15),
    height: wp(15),
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 60,
    alignSelf: 'center',
    marginTop: 20,
  },
  plusStyle: {
    fontSize: 10,
    color: '#5FBACF',
  },
  plusStyle1: {
    fontSize: 10,
    color: '#fff',
  },
  addnewItem: {
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#5FBACF',
    width: wp(15),
    height: wp(15),
    borderRadius: wp(7.5),
  },
  plusContainer: {
    marginVertical: 10,
    width: wp(15),
    height: wp(15),
    backgroundColor: '#5FBACF',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 60,
    alignSelf: 'center',
  },
  plusText: {
    color: '#fff',
    fontSize: 10,
  },
});

export default styles;
