import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  icon: {
    marginLeft: wp(4),
    marginTop: hp(4),
  },
  inputOptional: {
    color: '#fff',
    paddingLeft: 10,
  },
  bottomContainer: {
    height: hp(65),
    width: wp(100),
    backgroundColor: '#5FBACF',
    bottom: 0,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  bottomView: {
    marginTop: hp(4),
  },
  profileContainer: {
    alignItems: 'center',
  },
  profile: {
    width: wp(25),
    height: wp(25),
  },
  nameText: {
    fontSize: 6,
    color: '#5FBACF',
  },
  editName: {
    fontSize: 4,
    color: '#5FBACF',
  },
  ageView: {
    width: wp(70),
    padding: 15,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
  },
  age: {
    fontSize: 6,
    color: '#5FBACF',
  },
  ageContainer: {
    backgroundColor: '#5FBACF',
    position: 'absolute',
    width: wp(80),
    zIndex: 1,
    elevation: 10,
    justifyContent: 'center',
    flex: 1,
    alignItems: 'center',
    margin: wp(5),
  },
  medicationsstyle: {
    backgroundColor: '#5FBACF',
    width: wp(90),
    paddingVertical: 20,
    zIndex: 1,
    borderRadius: 10,
    borderColor: '#fff',
    borderWidth: 15,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginHorizontal: wp(2),
  },
  buttonView: {
    width: wp(18),
    marginLeft: wp(2),
    height: 50,
    borderRadius: 10,
    elevation: 1,
  },
  modals: {
    alignItems: 'center',
  },
  diagnosisView: {
    marginVertical: hp(4),
    width: wp(90),
    padding: 10,
    backgroundColor: '#fff',
    alignSelf: 'center',
    borderRadius: 10,
  },
  diagnosisView2: {
    backgroundColor: '#5FBACF',
    paddingVertical: 20,
    paddingLeft: 10,
  },
  diagnosisView3: {
    paddingLeft: 10,
    backgroundColor: '#5FBACF',
    paddingVertical: 5,
  },
  diagnosis: {
    fontSize: 6,
    color: '#5FBACF',
  },
  monthAgo: {
    fontSize: 3.5,
    color: '#5FBACF',
    alignSelf: 'center',
    width: wp(30),
  },
  daignoModal: {
    padding: 20,
    height: hp(20),
    alignItems: 'center',
    width: wp(80),
    backgroundColor: 'rgba(95, 186, 207, 0.9)',
    alignSelf: 'center',
    position: 'absolute',
    top: 50,
    zIndex: 1,
    borderRadius: 10,
  },
  edit: {
    fontSize: 6,
    color: '#fff',
    alignSelf: 'center',
    backgroundColor: '#94D1E0',
    paddingHorizontal: wp(2),
    marginVertical: hp(1),
    borderRadius: 5,
  },
  stomach: {
    width: 10,
    height: 10,
    backgroundColor: '#fff',
    alignSelf: 'center',
    borderRadius: 10,
    marginRight: 5,
    marginLeft: 5,
  },
  skin: {
    fontSize: 5,
    color: '#fff',
  },
  medicine: {
    fontSize: 5,
    color: '#fff',
    width: wp(40),
    marginTop: hp(2),
    marginLeft: wp(2),
  },
  reminder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  allReminders: {
    fontSize: 4,
    color: '#fff',
  },
  reminderContainer: {
    backgroundColor: '#5FBACF',
    paddingVertical: 15,
    borderRadius: 5,
  },
  saveDone: {
    backgroundColor: '#fff',
    width: wp(30),
  },
  milegram: {
    color: '#fff',
    alignSelf: 'flex-end',
    marginRight: wp(15),
    fontSize: 3,
    paddingBottom: 5,
  },
  viewMore: {
    marginVertical: hp(1),
    flex: 1,
    fontSize: 5,
    alignSelf: 'flex-end',
    color: '#1976d2',
    borderBottomWidth: 1,
    borderBottomColor: '#1976d2',
  },
  editList: {
    alignSelf: 'center',
    alignItems: 'center',
    marginRight: 20,
    marginLeft: 10,
    marginTop: 5,
  },
});

export default styles;
